### ISSUE TITLE
`setting_value` and `setting_key` not found in table

### ISSUE THREAD

**Issue by lezhnev74** [efriandika/laravel-settings#12]
I have this strange problem from nowhere.
It says:
`exception 'PDOException' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'setting_value' in 'field list'' in /disk1/.../vendor/laravel/framework/src/Illuminate/Database/Connection.php:319`

But migration defines structure with no `setting_value` or `setting_key` in it:

```
Schema::create('settings', function(Blueprint $table)
        {
            $table->string('key', 100)->index()->unique('key');
            $table->text('value', 65535)->nullable();
        });
```

So hows that possible? Its been working since april'15

**Comment by lezhnev74** [comment]
So as I can see you've changed table structure 3 months ago.
What would be the migration process here?

**Comment by lezhnev74** [comment]
Your migration changes the existing columns, so I had to do:
`composer require doctrine/dbal` in order to make it work.

P.s. just wonder what kind of purpose was behind this changes that costed me 2 hours of work?

**Comment by efriandika** [comment]
Hello lezhnev74, you can find the information in readme

**Comment by efriandika** [comment]
Table name = key make a problem with Ms SQLServer
