### ISSUE TITLE
Use multiple/custom driver for cache

### ISSUE THREAD

**Issue by m2sh** [efriandika/laravel-settings#16]
Can you add feature to using selective/custom cache driver and using laravel cache config for driver config.  
Also you could use [Laravel Cache](https://laravel.com/docs/5.2/cache) driver for get/set cache data.  

If you are agree with me, i can implement this feature and send pull request.

**Comment by efriandika** [comment]
Sure @m2sh .. Totally I agree with you.. But, Currently I have no time to work on that.. If you have time, you can do that and make a pull request.. Thank you so much for your effort :)
