### ISSUE TITLE
Non-static method Efriandika\LaravelSettings\Settings::set() should not be called statically

### ISSUE THREAD

**Issue by zanozik** [efriandika/laravel-settings#18]
**Non-static method Efriandika\LaravelSettings\Settings::set() should not be called statically**
Not sure what to do with it, since all I am trying to do is:

``` php
<?php namespace App\Http\Controllers;
use Efriandika\LaravelSettings\Settings;

class InvoiceController extends Controller {
    public function issue(){
        Settings::set('next_id', '18');
    }
}
```

Strange thing, that I have no problem working with `::set` inside `SettingController`.

**Comment by zanozik** [comment]
I just have figured it out. Turns out phpstorm "helper" inserted wrong declaration automatically. Instead of 
`use Efriandika\LaravelSettings\Facades\Settings;`
I got
 `use Efriandika\LaravelSettings\Settings;`

**Comment by nysso** [comment]
Use **Unisharp\Setting\SettingFacade**
instead of
_Unisharp\Setting\Setting_
