### ISSUE TITLE
The package wont install in laravel 5

### ISSUE THREAD

**Issue by indesignlatam** [efriandika/laravel-settings#2]
Mainly because illuminate/support requires 5.1.x and not 5.x

``` php
"require": {
        "php": ">=5.5.9",
        "illuminate/support": "5.1.x"
    },
```

**Comment by efriandika** [comment]
i'm sorry, i forgot to change '5' to '5.1.x' in readme.md
the latest package only supports 5.1.x.
You can use [v1.0.1](https://github.com/efriandika/laravel-settings/releases/tag/v1.0.1) for laravel 5.0
Thanks..
