### ISSUE TITLE
Fallback to Laravel default config

### ISSUE THREAD

**Issue by uyab** [efriandika/laravel-settings#3]
Hi there, would you like to add functionality so that if key not exist and I don't provide default value, it will fallback to default Laravel config? Maybe it can configureable via config file too ('fallback' => true/false).

Sample:

``` php
Settings::get('mail.driver'); // if mail.driver not exist, than the value from config/mail.php will returned
```

With this functionality, I can provide something like "Reset To Default" :D

**Comment by efriandika** [comment]
Thanks for your idea.. :)
if you have some code about that, please pull request :D

**Comment by efriandika** [comment]
Look at [v1.2.0](https://github.com/efriandika/laravel-settings/releases/tag/v1.2.0)
