### ISSUE TITLE
Maybe change value column to BLOB?

### ISSUE THREAD

**Issue by jordanlev** [efriandika/laravel-settings#4]
Hi, this is a great little library, thanks for providing it!

Since you are using PHP's serialize function to save data to the table, you might consider changing the column type from TEXT to BLOB. I've run into problems in the past if the table charset isn't unicode, then non-ascii characters wind up corrupting the serialized data. A more detailed explanation of the problem can be found here: https://www.jackreichert.com/2014/02/handling-a-php-unserialize-offset-error/

...but note that I've found a much easier solution than all the base_64_encode/decode stuff mentioned in that link is to just make the column a BLOB instead of TEXT.

**Comment by efriandika** [comment]
thanks for your idea, i will update this library asap.. :)

**Comment by jordanlev** [comment]
Upon further consideration, I wonder if the database table is even necessary at all. Since the settings are being written to the `settings.json` file, is there really any purpose to duplicating the data in the database as well?

**Comment by floodedcodeboy** [comment]
+1 for using either file OR db

**Comment by efriandika** [comment]
@jordanlev settings.json is just a cache

**Comment by jordanlev** [comment]
I'm curious what the purpose of the DB is, though... I understand that settings.json is being used as a cache, but since it's there why not just use it as the sole storage mechanism? I suppose this wouldn't work if the settings.json file gets deleted from time to time... but does this happen? (I'm still relatively new to Laravel, so I don't know how files in /storage are generally treated).
